[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Proxy /api/backend or /api/* to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Client-side routing SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
